### ISSUE TITLE
hacer el repo privado

### ISSUE THREAD

**Issue by mendezmariano** [brunograssano/Sistemas-operativos-fiuba#1]
Hola, Como va? podras hacer el repo privado, porque se supone que los labs y tp deberian hacerse sin ver los resultados.

Saludos
Dr. mendez

**Comment by brunograssano** [comment]
Hola, no estan los labs y TP en este repositorio. En el repositorio estan los apuntes que fui tomando durante la cursada, un resumen, y ejercicios de practica extra. Si aun asi quiere que quede privado digame

Saludos

**Comment by mendezmariano** [comment]
No
